apiVersion: v1
kind: Service
metadata:
  name: kbot-otel
  namespace: monitoring
spec:
  selector:
    app: kbot
  ports:
    - name: prometheus
      protocol: TCP
      port: 8889
      targetPort: 8889
  type: ClusterIP
