apiVersion: v1
kind: Service
metadata:
  name: kbot
  namespace: monitoring
spec:
  selector:
    app: kbot
  ports:
    - name: prometheus
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
